name: flutter_custom_lints_example
description: Example project demonstrating flutter_custom_lints usage
publish_to: none

environment:
  sdk: ^3.8.1

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_custom_lints: ^1.0.5