name: flutter_custom_lints
description: A collection of custom lint rules for Flutter and Dart projects that enforce best practices and prevent common coding mistakes.
version: 1.0.0
homepage: https://github.com/bahricanyesil/flutter-custom-lints
repository: https://github.com/bahricanyesil/flutter-custom-lints
issue_tracker: https://github.com/bahricanyesil/flutter-custom-lints/issues

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  custom_lint_builder: ^0.7.5
  analyzer: ^7.4.5
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  build_runner: ^2.4.15
  build_test: ^2.2.3
  build_web_compilers: ^4.1.5
  source_gen: ^2.0.0
